version: "3"
services:
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:${POSTGRES_PORT}"
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: $NODE_ENV
      PORT: $PORT
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
volumes:
  postgres:
